# Generated by Django 6.1.1 on 2026-09-28 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nombre', models.CharField(blank=True, max_length=150)),
                ('tipo_usuario', models.CharField(choices=[('administrador', 'Administrador'), ('recepcionista', 'Recepcionista'), ('operario', 'Operario'), ('cliente', 'Cliente')], max_length=20)),
                ('accion', models.CharField(choices=[('creado', 'Creado'), ('editado', 'Editado'), ('activado', 'Activado'), ('desactivado', 'Desactivado')], max_length=20)),
                ('detalle', models.CharField(blank=True, max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de auditoría',
                'verbose_name_plural': 'registros de auditoría',
                'ordering': ('-fecha',),
            },
        ),
    ]
