# Generated by Django 6.1.1 on 2026-10-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_registroauditoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroauditoria',
            name='accion',
            field=models.CharField(choices=[('creado', 'Creado'), ('editado', 'Editado'), ('activado', 'Activado'), ('desactivado', 'Desactivado'), ('inicio_sesion', 'Inicio de sesión')], max_length=20),
        ),
    ]
