# Generated by Django 6.1.1 on 2026-10-05 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa',
            name='unidad_cobro',
            field=models.CharField(choices=[('kilo', 'Kilo'), ('prenda', 'Prenda')], default='kilo', help_text='Unidad por la que se multiplica el valor.', max_length=10),
        ),
    ]
