# Generated by Django 6.1.1 on 2026-09-28 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('porcentaje', 'Porcentaje'), ('monto_fijo', 'Monto fijo')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('clasificacion_cliente', models.CharField(blank=True, choices=[('Ocasional', 'Ocasional'), ('Frecuente', 'Frecuente'), ('VIP', 'VIP')], help_text='Vacio = aplica a cualquier clasificacion de cliente.', max_length=30)),
                ('activa', models.BooleanField(default=True)),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('actualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-vigente_desde', 'nombre'),
                'constraints': [models.CheckConstraint(condition=models.Q(('valor__gte', 0)), name='regla_descuento_valor_no_negativo'), models.CheckConstraint(condition=models.Q(models.Q(('tipo', 'porcentaje'), _negated=True), ('valor__lte', 100), _connector='OR'), name='regla_descuento_porcentaje_no_supera_100'), models.CheckConstraint(condition=models.Q(('vigente_hasta__isnull', True), ('vigente_hasta__gt', models.F('vigente_desde')), _connector='OR'), name='regla_descuento_vigencia_coherente')],
            },
        ),
    ]
